---
title: "Assigment 2"
author: "Pavel Linder, Nikita Brancatisano"
date: "12/26/2019"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
```{r libraries, echo=FALSE, warning=FALSE, results='hide', message=FALSE}
library(gtools) # if problems calling library, install.packages("gtools", dependencies = T)
#library(qdap) # qualitative data analysis package (it masks %>%)
library(stringr)
library(tm) # framework for text mining; it loads NLP package
library(ggplot2)
```

## 0. Read input
```{r import, echo=TRUE}
train = read.table(file = 'train.tsv', sep = '\t', header = TRUE, stringsAsFactors = FALSE)
test = read.table(file = 'test.tsv', sep = '\t', header = TRUE)
length(which(!complete.cases(train)))
train$text_a[1:3]
```

# 1. Cleaning data
## Remove punctuation and stopwords
```{r punctuation, echo=TRUE}
train$text_a = as.character(train$text_a)
train$text_a = tm::removePunctuation(train$text_a)
train$text_a = tm::removeWords(x = train$text_a, stopwords(kind = "SMART"))
train$text_a = tm::stripWhitespace(train$text_a)
train$text_a[1:3]
```

## Anonymize proper nouns
```{r anonymize, echo=TRUE}

```

## Remove unknown symbols (non UTF-8 characters)
```{r symbols, echo=TRUE}
train$text_a = str_replace_all(train$text_a, "[^[:alnum:],[:blank:]/\\-]", "")
train$text_a[1:3]
```

# 2. Exploration
### Plot the frequency of words (without stemmization)
```{r frequency1, echo=TRUE}
corpus <- Corpus(VectorSource(train$text_a)) # turn into corpus
tdm <- TermDocumentMatrix(corpus)

wordFreq <- sort(rowSums(as.matrix(tdm)), decreasing=TRUE)
qplot(seq(length(wordFreq)),sort(wordFreq), xlab = "index", ylab = "Frequency")

findFreqTerms(tdm, lowfreq=50)
mostFreq <- subset(wordFreq, wordFreq >= 50)
qplot(seq(length(mostFreq)),sort(mostFreq), xlab = "index", ylab = "Frequency")

length(wordFreq)

length(wordFreq[wordFreq<10])

length(wordFreq[wordFreq<5])

length(wordFreq[wordFreq==1])


freq <- sort(unique(wordFreq), decreasing=FALSE)
occ <- vector()
for (i in 1:length(freq)) {
  occ[i] <- length(wordFreq[wordFreq == freq[i]])
}
qplot(freq[1:15], occ[1:15], xlab = "Frequency of word", ylab = "# of occurencies")

```

### Plot the frequency of words (with stemmization)

